2020-12-25 21:39:59,774 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:05,371 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:10,948 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:16,563 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:22,157 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:27,765 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:33,357 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:38,958 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:44,563 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:50,249 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:40:55,871 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:01,474 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:07,109 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:12,720 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:18,388 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:23,998 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:29,607 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:35,193 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:40,848 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:46,493 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:52,087 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:41:57,739 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:03,389 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:09,018 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:14,721 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:20,379 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:26,011 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:26,622 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:26,748 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:26,817 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:42:26,894 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:43:25,128 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:43:28,444 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:43:28,687 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:43:28,880 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:43:28,951 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:44:22,506 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-25 21:45:15,723 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-26 20:03:20,513 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-26 20:03:25,838 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-26 20:03:26,013 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-26 20:03:26,053 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2020-12-26 20:03:26,465 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2021-01-06 23:10:04,198 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2021-01-06 23:10:08,054 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2021-01-06 23:10:08,122 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2021-01-06 23:10:08,203 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2021-01-06 23:10:08,386 INFO: NWE startup [in /home/portfolio/ui/client/__init__.py:49]
2021-01-06 23:13:15,690 ERROR: Exception on /predict [POST] [in /home/portfolio/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/portfolio/ui/client/routes.py", line 106, in predict_word
    return jsonify({'prediction': r_ngram.zrange(request.form['key'],
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 2801, in zrange
    return self.execute_command(*pieces, **options)
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
2021-01-06 23:13:27,067 ERROR: Exception on /predict [POST] [in /home/portfolio/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/portfolio/ui/client/routes.py", line 106, in predict_word
    return jsonify({'prediction': r_ngram.zrange(request.form['key'],
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 2801, in zrange
    return self.execute_command(*pieces, **options)
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
2021-01-06 23:13:27,093 ERROR: Exception on /predict [POST] [in /home/portfolio/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/portfolio/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/portfolio/ui/client/routes.py", line 106, in predict_word
    return jsonify({'prediction': r_ngram.zrange(request.form['key'],
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 2801, in zrange
    return self.execute_command(*pieces, **options)
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/portfolio/venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
